"""
Django settings for pytest project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wpduq7lvh5nwe1e5x5!0g*@4smeo1@3m3lf$e9mizh_t_)pno='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',  # 必须包含
    'django.contrib.auth',   # admin依赖auth
    'django.contrib.contenttypes',  # admin依赖contenttypes
    'django.contrib.sessions',  # 可选但推荐
    'django.contrib.messages',  # 可选但推荐
    'django.contrib.staticfiles',
    # 你的其他应用...
    'simpleui',
    'django_celery_results',
    'django_celery_beat'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pytest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pytest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'pytest',      # 数据库名称
        'USER': 'root',     # MySQL 用户名
        'PASSWORD': 'root', # MySQL 密码
        'HOST': 'localhost',               # 数据库主机（本地用 'localhost'）
        'PORT': '3306',                    # MySQL 默认端口
        'OPTIONS': {
            'charset': 'utf8mb4',          # 避免中文乱码
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",  # 严格模式
        },
        'TIME_ZONE': 'Asia/Shanghai',      # 时区设置（可选）
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------- celery 相关配置 ----------------------
# Broker配置，使用Redis作为消息中间件
BROKER_URL = 'redis://127.0.0.1:6379/1'
# BACKEND配置，使用Redis作为结果仓库
RESULT_BACKEND = 'redis://127.0.0.1:6379/2'

# 指定 Celery 能够接受的内容类型列表
ACCEPT_CONTENT = ['json']
# 任务将以json格式进行序列化
TASK_SERIALIZER = 'json'
# 结果以json格式进行序列化存储或传输
RESULT_SERIALIZER = 'json'

# 任务结果过期时间(单位:秒)
TASK_RESULT_EXPIRES = 60 * 60 * 24
# 时区配置
TIMEZONE = "Asia/Shanghai"

# 配置定时任务
import datetime

BEAT_SCHEDULE = {
    # 自定义周期执行的任务
    'add-every-10-seconds': {
        # 执行的任务
        'task': 'django_celery.tasks.add',
        # 执行时间设置
        # 'schedule': 1.0,  # 1秒执行一次
        # 'schedule': crontab(minute='*/1'),  # 1分钟执行 * 次
        # 'schedule': crontab(month_of_year="4", day_of_month="11", hour="8", minute="42"), # 每年4月11号，8点42分执行
        'schedule': datetime.timedelta(seconds=10),  # 每10秒执行一次
        'args': (123, 321)
    }
}
